substitutions:
  _NEXT_PUBLIC_API_URL: ''
  _IMAGE: ''

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-t'
      - '${_IMAGE}'
      - '.'

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
